env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - EMU_FLAVOR=default
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - API=34
    - ABI=x86
    - AUDIO=-no-audio

language: android
dist: xenial
jdk:
  - openjdk17

android:
  components:
    - tools

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  # Install Ruby 2.6.0
  - rvm install 2.6.0
  - rvm use 2.6.0 --default
  - gem install bundler -v 2.4.22
  - bundle install
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platform-tools" --sdk_root=$ANDROID_HOME >/dev/null
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "tools" --sdk_root=$ANDROID_HOME >/dev/null
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;34.0.0" --sdk_root=$ANDROID_HOME >/dev/null
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-$API" --sdk_root=$ANDROID_HOME >/dev/null
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --channel=4 "emulator" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "extras;android;m2repository" --sdk_root=$ANDROID_HOME >/dev/null

before_script:
  - chmod +x gradlew

script:
  - "./gradlew clean assembleDebug"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_07c92ad84bea_key -iv $encrypted_07c92ad84bea_iv -in signing.tar.enc -out signing.tar -d
  - tar xvf signing.tar
  - "./gradlew clean assembleRelease"
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install multipart-post -v 2.3.0

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file: app/build/outputs/apk/release/*.apk
  skip_cleanup: true
  on:
    repo: TheCacophonyProject/bird-monitor
    tags: true
